#!/usr/bin/env python3

import subprocess
import sys
from operator import sub
from pathlib import Path
from xml.parsers.expat import version_info

import tomllib


def run_git(*args: str) -> str:
    result = subprocess.run(["git", *args], capture_output=True, text=True, check=True)
    return result.stdout.strip()


def cmake_escape(v: str) -> str:
    return v.replace("\\", "\\\\").replace('"', '\\"')


def main():
    if len(sys.argv) != 3:
        print(
            "Usage: generate_metadata.py <toml_file> <cmake_output>",
            file=sys.stderr,
        )
        sys.exit(1)

    metadata_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    with metadata_path.open("rb") as f:
        metadata = tomllib.load(f)

    # TOML sections
    app = metadata["app"]
    version = app["version"]
    protocol = metadata["protocol"]

    # config consts
    app_name = app["name"]

    version_major = version["major"]
    version_minor = version["minor"]
    version_patch = version["patch"]

    protocol_version = protocol["version"]

    # Git metadadata
    git_sha = run_git("rev-parse", "HEAD")
    git_branch = run_git("rev-parse", "--abbrev-ref", "HEAD")

    # CMake output
    output = f"""
# Generated by generate_metadata.py
set(APP_NAME "{cmake_escape(app_name)}")
set(APP_VERSION_MAJOR {version_major})
set(APP_VERSION_MINOR {version_minor})
set(APP_VERSION_PATCH {version_patch})
set(APP_PROTOCOL_VERSION {protocol_version})
set(GIT_SHA "{git_sha}")
set(GIT_BRANCH "{git_branch}")
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="utf-8")

    print(f"Metadata generated and written to {output_path}")
    sys.exit(0)


if __name__ == "__main__":
    main()
